/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    drivers: Driver;
    tariffs: Tariff;
    vehicles: Vehicle;
    bookings: Booking;
    customers: Customer;
    coupons: Coupon;
    'vehicle-images': VehicleImage;
    'vehicle-icons': VehicleIcon;
    'slider-images': SliderImage;
    contacts: Contact;
    alerts: Alert;
    reviews: Review;
    'revenue-settlements': RevenueSettlement;
    'payment-methods': PaymentMethod;
    invoices: Invoice;
    'trip-otps': TripOtp;
    'trip-sharing': TripSharing;
    'driver-offline-logs': DriverOfflineLog;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    customers: {
      bookings: 'bookings';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    drivers: DriversSelect<false> | DriversSelect<true>;
    tariffs: TariffsSelect<false> | TariffsSelect<true>;
    vehicles: VehiclesSelect<false> | VehiclesSelect<true>;
    bookings: BookingsSelect<false> | BookingsSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    coupons: CouponsSelect<false> | CouponsSelect<true>;
    'vehicle-images': VehicleImagesSelect<false> | VehicleImagesSelect<true>;
    'vehicle-icons': VehicleIconsSelect<false> | VehicleIconsSelect<true>;
    'slider-images': SliderImagesSelect<false> | SliderImagesSelect<true>;
    contacts: ContactsSelect<false> | ContactsSelect<true>;
    alerts: AlertsSelect<false> | AlertsSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    'revenue-settlements': RevenueSettlementsSelect<false> | RevenueSettlementsSelect<true>;
    'payment-methods': PaymentMethodsSelect<false> | PaymentMethodsSelect<true>;
    invoices: InvoicesSelect<false> | InvoicesSelect<true>;
    'trip-otps': TripOtpsSelect<false> | TripOtpsSelect<true>;
    'trip-sharing': TripSharingSelect<false> | TripSharingSelect<true>;
    'driver-offline-logs': DriverOfflineLogsSelect<false> | DriverOfflineLogsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'booking-report': BookingReport;
    'customer-report': CustomerReport;
    'payment-settings': PaymentSetting;
    'vehicle-report': VehicleReport;
    'cancellation-control': CancellationControl;
    'general-settings': GeneralSetting;
  };
  globalsSelect: {
    'booking-report': BookingReportSelect<false> | BookingReportSelect<true>;
    'customer-report': CustomerReportSelect<false> | CustomerReportSelect<true>;
    'payment-settings': PaymentSettingsSelect<false> | PaymentSettingsSelect<true>;
    'vehicle-report': VehicleReportSelect<false> | VehicleReportSelect<true>;
    'cancellation-control': CancellationControlSelect<false> | CancellationControlSelect<true>;
    'general-settings': GeneralSettingsSelect<false> | GeneralSettingsSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    username: string;
  };
  login: {
    password: string;
    username: string;
  };
  registerFirstUser: {
    password: string;
    username: string;
  };
  unlock: {
    username: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  password?: string | null;
  fullName?: string | null;
  phoneNumber?: string | null;
  active?: boolean | null;
  role?: ('superadmin' | 'admin' | 'accounts' | 'driver') | null;
  driverProfile?: (string | null) | Driver;
  updatedAt: string;
  createdAt: string;
  email?: string | null;
  username: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "drivers".
 */
export interface Driver {
  id: string;
  name: string;
  phone: string;
  address: string;
  /**
   * Years of driving experience
   */
  experience: number;
  aadharNo?: string | null;
  panNo?: string | null;
  license?: string | null;
  /**
   * Driver photo
   */
  photo?: (string | null) | Media;
  status: 'available' | 'not_available' | 'onduty' | 'offline';
  connectionStatus?: ('online' | 'offline' | 'syncing') | null;
  lastSeen?: string | null;
  /**
   * @minItems 2
   * @maxItems 2
   */
  location?: [number, number] | null;
  lastUpdated?: string | null;
  assignedVehicle?: (string | null) | Vehicle;
  user?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  title?: string | null;
  alt: string;
  category?: ('drivers' | 'vehicles' | 'banners' | 'other') | null;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vehicles".
 */
export interface Vehicle {
  id: string;
  name: string;
  number: string;
  seatCount?: number | null;
  ownerName: string;
  /**
   * Each driver can be assigned to only one vehicle.
   */
  driver?: (string | null) | Driver;
  status: 'available' | 'not_available' | 'driving';
  lastFc: string;
  image?: (string | null) | Media;
  icon?: (string | null) | Media;
  category: 'tariff' | 'attachment';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tariffs".
 */
export interface Tariff {
  id: string;
  name: string;
  description?: string | null;
  status: 'active' | 'draft' | 'pending_review';
  vehicleType: string | Vehicle;
  oneway: {
    perKmRate: number;
    bata: number;
    minDistance: number;
    extras?: number | null;
  };
  roundtrip: {
    perKmRate: number;
    bata: number;
    minDistance: number;
    extras?: number | null;
  };
  packages: {
    hours: number;
    km: number;
    baseRate: number;
    baseBata: number;
    extraKmRate: number;
    extraHourRate: number;
    nightBata?: number | null;
    otherExtras?: number | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings".
 */
export interface Booking {
  id: string;
  customerName: string;
  customerPhone: string;
  customer?: (string | null) | Customer;
  vehicle: string | Vehicle;
  tripType: 'oneway' | 'roundtrip' | 'packages' | 'multilocation';
  driver?: (string | null) | Driver;
  /**
   * @minItems 2
   * @maxItems 2
   */
  pickupLocation: [number, number];
  pickupLocationName: string;
  /**
   * @minItems 2
   * @maxItems 2
   */
  dropoffLocation?: [number, number] | null;
  dropoffLocationName?: string | null;
  tourLocations?:
    | {
        name: string;
        /**
         * @minItems 2
         * @maxItems 2
         */
        point: [number, number];
        id?: string | null;
      }[]
    | null;
  pickupDateTime: string;
  dropDateTime?: string | null;
  estimatedFare?: number | null;
  couponCode?: string | null;
  discountAmount?: number | null;
  distanceKm?: number | null;
  status?: ('pending' | 'confirmed' | 'cancelled' | 'completed') | null;
  tripStatus?: ('not_started' | 'started' | 'completed' | 'cancelled') | null;
  otpVerified?: boolean | null;
  sharingToken?: string | null;
  paymentStatus?: ('unpaid' | 'partial' | 'paid' | 'failed') | null;
  paymentAmount?: number | null;
  sosTriggered?: boolean | null;
  paymentType?: ('minimum' | 'full') | null;
  razorpayOrderId?: string | null;
  razorpayPaymentId?: string | null;
  razorpaySignature?: string | null;
  bookingCode?: string | null;
  notes?: string | null;
  reallocationHistory?:
    | {
        previousDriver?: (string | null) | Driver;
        timestamp?: string | null;
        reason?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: string;
  name: string;
  phone: string;
  email?: string | null;
  accountType?: ('individual' | 'corporate') | null;
  bookings?: {
    docs?: (string | Booking)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coupons".
 */
export interface Coupon {
  id: string;
  name: string;
  percentage: number;
  tariffScope: 'all' | 'oneway' | 'roundtrip' | 'packages';
  vehicleScope: 'all' | 'specific';
  vehicles?: (string | Vehicle)[] | null;
  startDate?: string | null;
  expiryDate?: string | null;
  /**
   * Maximum number of times this coupon can be used (leave empty for unlimited)
   */
  usageLimit?: number | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vehicle-images".
 */
export interface VehicleImage {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vehicle-icons".
 */
export interface VehicleIcon {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "slider-images".
 */
export interface SliderImage {
  id: string;
  image: string | Media;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Manage customer, partner, and driver inquiries.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contacts".
 */
export interface Contact {
  id: string;
  name: string;
  phone: string;
  inquiryType: 'service' | 'billing' | 'partnership' | 'emergency';
  message: string;
  status?: ('new' | 'pending' | 'resolved' | 'urgent') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "alerts".
 */
export interface Alert {
  id: string;
  title: string;
  message: string;
  type: 'info' | 'warning' | 'emergency' | 'payment_fail' | 'booking';
  triggeredBy?: (string | null) | User;
  isRead?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: string;
  booking: string | Booking;
  user: string | User;
  /**
   * Star rating from 1 to 5
   */
  rating: number;
  comment: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "revenue-settlements".
 */
export interface RevenueSettlement {
  id: string;
  tripId: string;
  driverName: string;
  customerName: string;
  distanceKm: number;
  timeMinutes: number;
  baseFare: number;
  distanceFare?: number | null;
  timeFare?: number | null;
  totalFare: number;
  commission: number;
  driverEarnings: number;
  platformRevenue: number;
  paymentMethod?: ('cash' | 'upi' | 'card') | null;
  status?: ('pending' | 'settled') | null;
  walletBalance?: number | null;
  payoutAmount?: number | null;
  settlementDate?: string | null;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payment-methods".
 */
export interface PaymentMethod {
  id: string;
  name: string;
  type: 'cash' | 'upi' | 'card' | 'netbanking' | 'wallet';
  isActive?: boolean | null;
  processingFee?: number | null;
  minimumAmount?: number | null;
  maximumAmount?: number | null;
  currency?: string | null;
  config?: {
    upiId?: string | null;
    merchantId?: string | null;
    apiKey?: string | null;
    apiSecret?: string | null;
  };
  supportedBanks?:
    | {
        bankName: string;
        id?: string | null;
      }[]
    | null;
  icon?: string | null;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invoices".
 */
export interface Invoice {
  id: string;
  invoiceNumber?: string | null;
  booking: string | Booking;
  customer: string | Customer;
  driver: string | Driver;
  date: string;
  baseFare: number;
  tax?: number | null;
  totalAmount?: number | null;
  paymentMethod?: (string | null) | PaymentMethod;
  status?: ('pending' | 'paid' | 'overdue') | null;
  pickupLocation?: string | null;
  dropoffLocation?: string | null;
  distance?: number | null;
  receiptNumber?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trip-otps".
 */
export interface TripOtp {
  id: string;
  booking: string | Booking;
  otp: string;
  expiresAt: string;
  verified?: boolean | null;
  deliveryMethod?: ('sms' | 'whatsapp' | 'email') | null;
  deliveryStatus?: ('pending' | 'sent' | 'failed') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trip-sharing".
 */
export interface TripSharing {
  id: string;
  booking: string | Booking;
  shareToken: string;
  active?: boolean | null;
  expiresAt: string;
  views?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "driver-offline-logs".
 */
export interface DriverOfflineLog {
  id: string;
  driver: string | Driver;
  trip?: (string | null) | Booking;
  offlineCoordinates?:
    | {
        /**
         * @minItems 2
         * @maxItems 2
         */
        location: [number, number];
        timestamp: string;
        speed?: number | null;
        id?: string | null;
      }[]
    | null;
  syncedAt?: string | null;
  batchSize?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'drivers';
        value: string | Driver;
      } | null)
    | ({
        relationTo: 'tariffs';
        value: string | Tariff;
      } | null)
    | ({
        relationTo: 'vehicles';
        value: string | Vehicle;
      } | null)
    | ({
        relationTo: 'bookings';
        value: string | Booking;
      } | null)
    | ({
        relationTo: 'customers';
        value: string | Customer;
      } | null)
    | ({
        relationTo: 'coupons';
        value: string | Coupon;
      } | null)
    | ({
        relationTo: 'vehicle-images';
        value: string | VehicleImage;
      } | null)
    | ({
        relationTo: 'vehicle-icons';
        value: string | VehicleIcon;
      } | null)
    | ({
        relationTo: 'slider-images';
        value: string | SliderImage;
      } | null)
    | ({
        relationTo: 'contacts';
        value: string | Contact;
      } | null)
    | ({
        relationTo: 'alerts';
        value: string | Alert;
      } | null)
    | ({
        relationTo: 'reviews';
        value: string | Review;
      } | null)
    | ({
        relationTo: 'revenue-settlements';
        value: string | RevenueSettlement;
      } | null)
    | ({
        relationTo: 'payment-methods';
        value: string | PaymentMethod;
      } | null)
    | ({
        relationTo: 'invoices';
        value: string | Invoice;
      } | null)
    | ({
        relationTo: 'trip-otps';
        value: string | TripOtp;
      } | null)
    | ({
        relationTo: 'trip-sharing';
        value: string | TripSharing;
      } | null)
    | ({
        relationTo: 'driver-offline-logs';
        value: string | DriverOfflineLog;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  password?: T;
  fullName?: T;
  phoneNumber?: T;
  active?: T;
  role?: T;
  driverProfile?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  username?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  title?: T;
  alt?: T;
  category?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "drivers_select".
 */
export interface DriversSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  address?: T;
  experience?: T;
  aadharNo?: T;
  panNo?: T;
  license?: T;
  photo?: T;
  status?: T;
  connectionStatus?: T;
  lastSeen?: T;
  location?: T;
  lastUpdated?: T;
  assignedVehicle?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tariffs_select".
 */
export interface TariffsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  status?: T;
  vehicleType?: T;
  oneway?:
    | T
    | {
        perKmRate?: T;
        bata?: T;
        minDistance?: T;
        extras?: T;
      };
  roundtrip?:
    | T
    | {
        perKmRate?: T;
        bata?: T;
        minDistance?: T;
        extras?: T;
      };
  packages?:
    | T
    | {
        hours?: T;
        km?: T;
        baseRate?: T;
        baseBata?: T;
        extraKmRate?: T;
        extraHourRate?: T;
        nightBata?: T;
        otherExtras?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vehicles_select".
 */
export interface VehiclesSelect<T extends boolean = true> {
  name?: T;
  number?: T;
  seatCount?: T;
  ownerName?: T;
  driver?: T;
  status?: T;
  lastFc?: T;
  image?: T;
  icon?: T;
  category?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings_select".
 */
export interface BookingsSelect<T extends boolean = true> {
  customerName?: T;
  customerPhone?: T;
  customer?: T;
  vehicle?: T;
  tripType?: T;
  driver?: T;
  pickupLocation?: T;
  pickupLocationName?: T;
  dropoffLocation?: T;
  dropoffLocationName?: T;
  tourLocations?:
    | T
    | {
        name?: T;
        point?: T;
        id?: T;
      };
  pickupDateTime?: T;
  dropDateTime?: T;
  estimatedFare?: T;
  couponCode?: T;
  discountAmount?: T;
  distanceKm?: T;
  status?: T;
  tripStatus?: T;
  otpVerified?: T;
  sharingToken?: T;
  paymentStatus?: T;
  paymentAmount?: T;
  sosTriggered?: T;
  paymentType?: T;
  razorpayOrderId?: T;
  razorpayPaymentId?: T;
  razorpaySignature?: T;
  bookingCode?: T;
  notes?: T;
  reallocationHistory?:
    | T
    | {
        previousDriver?: T;
        timestamp?: T;
        reason?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  email?: T;
  accountType?: T;
  bookings?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coupons_select".
 */
export interface CouponsSelect<T extends boolean = true> {
  name?: T;
  percentage?: T;
  tariffScope?: T;
  vehicleScope?: T;
  vehicles?: T;
  startDate?: T;
  expiryDate?: T;
  usageLimit?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vehicle-images_select".
 */
export interface VehicleImagesSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vehicle-icons_select".
 */
export interface VehicleIconsSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "slider-images_select".
 */
export interface SliderImagesSelect<T extends boolean = true> {
  image?: T;
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contacts_select".
 */
export interface ContactsSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  inquiryType?: T;
  message?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "alerts_select".
 */
export interface AlertsSelect<T extends boolean = true> {
  title?: T;
  message?: T;
  type?: T;
  triggeredBy?: T;
  isRead?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  booking?: T;
  user?: T;
  rating?: T;
  comment?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "revenue-settlements_select".
 */
export interface RevenueSettlementsSelect<T extends boolean = true> {
  tripId?: T;
  driverName?: T;
  customerName?: T;
  distanceKm?: T;
  timeMinutes?: T;
  baseFare?: T;
  distanceFare?: T;
  timeFare?: T;
  totalFare?: T;
  commission?: T;
  driverEarnings?: T;
  platformRevenue?: T;
  paymentMethod?: T;
  status?: T;
  walletBalance?: T;
  payoutAmount?: T;
  settlementDate?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payment-methods_select".
 */
export interface PaymentMethodsSelect<T extends boolean = true> {
  name?: T;
  type?: T;
  isActive?: T;
  processingFee?: T;
  minimumAmount?: T;
  maximumAmount?: T;
  currency?: T;
  config?:
    | T
    | {
        upiId?: T;
        merchantId?: T;
        apiKey?: T;
        apiSecret?: T;
      };
  supportedBanks?:
    | T
    | {
        bankName?: T;
        id?: T;
      };
  icon?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invoices_select".
 */
export interface InvoicesSelect<T extends boolean = true> {
  invoiceNumber?: T;
  booking?: T;
  customer?: T;
  driver?: T;
  date?: T;
  baseFare?: T;
  tax?: T;
  totalAmount?: T;
  paymentMethod?: T;
  status?: T;
  pickupLocation?: T;
  dropoffLocation?: T;
  distance?: T;
  receiptNumber?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trip-otps_select".
 */
export interface TripOtpsSelect<T extends boolean = true> {
  booking?: T;
  otp?: T;
  expiresAt?: T;
  verified?: T;
  deliveryMethod?: T;
  deliveryStatus?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trip-sharing_select".
 */
export interface TripSharingSelect<T extends boolean = true> {
  booking?: T;
  shareToken?: T;
  active?: T;
  expiresAt?: T;
  views?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "driver-offline-logs_select".
 */
export interface DriverOfflineLogsSelect<T extends boolean = true> {
  driver?: T;
  trip?: T;
  offlineCoordinates?:
    | T
    | {
        location?: T;
        timestamp?: T;
        speed?: T;
        id?: T;
      };
  syncedAt?: T;
  batchSize?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "booking-report".
 */
export interface BookingReport {
  id: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customer-report".
 */
export interface CustomerReport {
  id: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payment-settings".
 */
export interface PaymentSetting {
  id: string;
  /**
   * Minimum amount required to confirm a booking.
   */
  minimumPayment?: number | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vehicle-report".
 */
export interface VehicleReport {
  id: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cancellation-control".
 */
export interface CancellationControl {
  id: string;
  penaltyAmount: number;
  rules: string;
  allowGracePeriod?: boolean | null;
  trackingEnabled?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "general-settings".
 */
export interface GeneralSetting {
  id: string;
  systemName: string;
  /**
   * Enter number with country code (e.g. 91xxxxxxxxxx)
   */
  whatsappNumber: string;
  supportEmail?: string | null;
  currencySymbol?: string | null;
  whatsappConfig?: {
    /**
     * The endpoint for your custom WhatsApp API
     */
    apiEndpoint?: string | null;
    /**
     * Authentication key for the API
     */
    apiKey?: string | null;
    /**
     * Use {name} and {link} as placeholders
     */
    messageTemplate?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "booking-report_select".
 */
export interface BookingReportSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customer-report_select".
 */
export interface CustomerReportSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payment-settings_select".
 */
export interface PaymentSettingsSelect<T extends boolean = true> {
  minimumPayment?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vehicle-report_select".
 */
export interface VehicleReportSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cancellation-control_select".
 */
export interface CancellationControlSelect<T extends boolean = true> {
  penaltyAmount?: T;
  rules?: T;
  allowGracePeriod?: T;
  trackingEnabled?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "general-settings_select".
 */
export interface GeneralSettingsSelect<T extends boolean = true> {
  systemName?: T;
  whatsappNumber?: T;
  supportEmail?: T;
  currencySymbol?: T;
  whatsappConfig?:
    | T
    | {
        apiEndpoint?: T;
        apiKey?: T;
        messageTemplate?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}